import { createHash } from 'node:crypto';
import { mkdir, readdir, readFile, stat, writeFile } from 'node:fs/promises';
import https from 'node:https';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pagesDir = path.join(rootDir, 'src/pages');
const fontDir = path.join(rootDir, 'public/assets/fonts');
const outputFile = path.join(rootDir, 'src/generated/localFontUrls.js');

const fontUrlPattern = /https?:\/\/[^\s"'<>),;]+?\.(?:woff2?|ttf|otf)(?:\?[^"'<>),;\s]+)?/gi;

function getFontFileName(url) {
  const parsedUrl = new URL(url);
  const ext = path.extname(parsedUrl.pathname) || '.font';
  const baseName = path.basename(parsedUrl.pathname, ext).replace(/[^a-z0-9-]+/gi, '-').slice(0, 48) || 'font';
  const hash = createHash('sha256').update(url).digest('hex').slice(0, 12);

  return `${baseName}-${hash}${ext}`;
}

async function collectFontUrls() {
  const files = (await readdir(pagesDir)).filter((file) => file.endsWith('.jsx'));
  const urls = new Set();

  for (const file of files) {
    const source = await readFile(path.join(pagesDir, file), 'utf8');

    for (const match of source.matchAll(fontUrlPattern)) {
      urls.add(match[0]);
    }
  }

  return [...urls].sort();
}

async function fileExists(filePath) {
  try {
    const stats = await stat(filePath);
    return stats.size > 0;
  } catch (_error) {
    return false;
  }
}

function download(url, destination) {
  return new Promise((resolve, reject) => {
    const request = https.get(url, (response) => {
      if ([301, 302, 303, 307, 308].includes(response.statusCode) && response.headers.location) {
        response.resume();
        download(new URL(response.headers.location, url).href, destination).then(resolve, reject);
        return;
      }

      if (response.statusCode !== 200) {
        response.resume();
        reject(new Error(`Failed to download ${url}: ${response.statusCode}`));
        return;
      }

      const chunks = [];
      response.on('data', (chunk) => chunks.push(chunk));
      response.on('end', async () => {
        try {
          await writeFile(destination, Buffer.concat(chunks));
          resolve();
        } catch (error) {
          reject(error);
        }
      });
    });

    request.on('error', reject);
    request.setTimeout(30000, () => {
      request.destroy(new Error(`Timed out downloading ${url}`));
    });
  });
}

async function main() {
  await mkdir(fontDir, { recursive: true });
  await mkdir(path.dirname(outputFile), { recursive: true });

  const urls = await collectFontUrls();
  const entries = [];

  for (const url of urls) {
    const fileName = getFontFileName(url);
    const destination = path.join(fontDir, fileName);

    if (!(await fileExists(destination))) {
      await download(url, destination);
    }

    entries.push([url, fileName]);
  }

  const source = `// Generated by scripts/localize-fonts.mjs. Do not edit by hand.\n` +
    `const localFontFiles = ${JSON.stringify(Object.fromEntries(entries), null, 2)};\n\n` +
    `export function localizeFontUrls(value) {\n` +
    `  if (!value) {\n` +
    `    return value;\n` +
    `  }\n\n` +
    `  const publicUrl = process.env.PUBLIC_URL || '';\n` +
    `  let localizedValue = value;\n\n` +
    `  Object.entries(localFontFiles).forEach(([remoteUrl, fileName]) => {\n` +
    `    localizedValue = localizedValue.split(remoteUrl).join(\`\${publicUrl}/assets/fonts/\${fileName}\`);\n` +
    `  });\n\n` +
    `  return localizedValue;\n` +
    `}\n`;

  await writeFile(outputFile, source);
  console.log(`Localized ${entries.length} font files.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
